export default {
        "code":200,
        "msg":"success",
        "data":[
            {
                "id":"1",
                "pid":"0",
                "children":[
                    {
                        "id":"1133013573031813121",
                        "pid":"1133003248421167105",
                        "children":[
                            {
                                "id":"1133009809843544066",
                                "pid":"1133013573031813121",
                                "children":[
    
                                ],
                                "name":"商品列表",
                                "url":"mggoods/goods/list",
                                "type":0,
                                "icon":"",
                                "permissions":"",
                                "sort":1,
                                "createDate":null,
                                "resourceList":null,
                                "parentName":null
                            },
                            {
                                "id":"1133010710348029953",
                                "pid":"1133013573031813121",
                                "children":[
    
                                ],
                                "name":"商品添加",
                                "url":"mggoods/goods/add",
                                "type":0,
                                "icon":"",
                                "permissions":"",
                                "sort":2,
                                "createDate":null,
                                "resourceList":null,
                                "parentName":null
                            },
                            {
                                "id":"1133011570830467074",
                                "pid":"1133013573031813121",
                                "children":[
    
                                ],
                                "name":"商品审核",
                                "url":"mggoods/goods/examine",
                                "type":0,
                                "icon":"",
                                "permissions":"",
                                "sort":3,
                                "createDate":null,
                                "resourceList":null,
                                "parentName":null
                            },
                            {
                                "id":"1133011744239771649",
                                "pid":"1133013573031813121",
                                "children":[
    
                                ],
                                "name":"价格管理",
                                "url":"mggoods/goods/price",
                                "type":0,
                                "icon":"",
                                "permissions":"",
                                "sort":4,
                                "createDate":null,
                                "resourceList":null,
                                "parentName":null
                            },
                            {
                                "id":"1133012145286537218",
                                "pid":"1133013573031813121",
                                "children":[
    
                                ],
                                "name":"库存管理",
                                "url":"mggoods/goods/stock",
                                "type":0,
                                "icon":"",
                                "permissions":"",
                                "sort":5,
                                "createDate":null,
                                "resourceList":null,
                                "parentName":null
                            },
                            {
                                "id":"1133012500376313857",
                                "pid":"1133013573031813121",
                                "children":[
    
                                ],
                                "name":"售后说明",
                                "url":"mggoods/goods/aftersale",
                                "type":0,
                                "icon":"",
                                "permissions":"",
                                "sort":6,
                                "createDate":null,
                                "resourceList":null,
                                "parentName":null
                            }
                        ],
                        "name":"商品管理",
                        "url":"",
                        "type":0,
                        "icon":"icon-filedone",
                        "permissions":"",
                        "sort":1,
                        "createDate":null,
                        "resourceList":null,
                        "parentName":null
                    },
                    {
                        "id":"1133015611367088130",
                        "pid":"1133003248421167105",
                        "children":[
                            {
                                "id":"1133015981615079426",
                                "pid":"1133015611367088130",
                                "children":[
    
                                ],
                                "name":"后台分类",
                                "url":"mggoods/category/backstage",
                                "type":0,
                                "icon":"",
                                "permissions":"",
                                "sort":1,
                                "createDate":null,
                                "resourceList":null,
                                "parentName":null
                            },
                            {
                                "id":"1133017094632366081",
                                "pid":"1133015611367088130",
                                "children":[
    
                                ],
                                "name":"展示分类",
                                "url":"mggoods/category/show",
                                "type":0,
                                "icon":"",
                                "permissions":"",
                                "sort":3,
                                "createDate":null,
                                "resourceList":null,
                                "parentName":null
                            }
                        ],
                        "name":"类目管理",
                        "url":"",
                        "type":0,
                        "icon":"icon-file-zip",
                        "permissions":"",
                        "sort":2,
                        "createDate":null,
                        "resourceList":null,
                        "parentName":null
                    },
                    {
                        "id":"1133210434673958914",
                        "pid":"1133003248421167105",
                        "children":[
                            {
                                "id":"1133213613671178241",
                                "pid":"1133210434673958914",
                                "children":[
    
                                ],
                                "name":"品牌列表",
                                "url":"mggoods/brand/list",
                                "type":0,
                                "icon":"",
                                "permissions":"",
                                "sort":1,
                                "createDate":null,
                                "resourceList":null,
                                "parentName":null
                            }
                        ],
                        "name":"品牌管理",
                        "url":"",
                        "type":0,
                        "icon":"icon-creditcard",
                        "permissions":"",
                        "sort":3,
                        "createDate":null,
                        "resourceList":null,
                        "parentName":null
                    },
                    {
                        "id":"1133221225112395778",
                        "pid":"1133003248421167105",
                        "children":[
                            {
                                "id":"1133221542843506690",
                                "pid":"1133221225112395778",
                                "children":[
    
                                ],
                                "name":"规格列表",
                                "url":"mggoods/specs/list",
                                "type":0,
                                "icon":"",
                                "permissions":"",
                                "sort":0,
                                "createDate":null,
                                "resourceList":null,
                                "parentName":null
                            },
                            {
                                "id":"1133221651408871426",
                                "pid":"1133221225112395778",
                                "children":[
    
                                ],
                                "name":"规格分组",
                                "url":"mggoods/specs/group",
                                "type":0,
                                "icon":"",
                                "permissions":"",
                                "sort":0,
                                "createDate":null,
                                "resourceList":null,
                                "parentName":null
                            }
                        ],
                        "name":"规格管理",
                        "url":"",
                        "type":0,
                        "icon":"icon-solution",
                        "permissions":"",
                        "sort":4,
                        "createDate":null,
                        "resourceList":null,
                        "parentName":null
                    },
                    {
                        "id":"1133222486461243393",
                        "pid":"1133003248421167105",
                        "children":[
                            {
                                "id":"1133222725100363777",
                                "pid":"1133222486461243393",
                                "children":[
    
                                ],
                                "name":"属性列表",
                                "url":"mggoods/attribute/list",
                                "type":0,
                                "icon":"",
                                "permissions":"",
                                "sort":1,
                                "createDate":null,
                                "resourceList":null,
                                "parentName":null
                            },
                            {
                                "id":"1133222849646026753",
                                "pid":"1133222486461243393",
                                "children":[
    
                                ],
                                "name":"属性分组",
                                "url":"mggoods/attribute/group",
                                "type":0,
                                "icon":"",
                                "permissions":"",
                                "sort":2,
                                "createDate":null,
                                "resourceList":null,
                                "parentName":null
                            }
                        ],
                        "name":"属性管理",
                        "url":"",
                        "type":0,
                        "icon":"icon-read",
                        "permissions":"",
                        "sort":5,
                        "createDate":null,
                        "resourceList":null,
                        "parentName":null
                    },
                    {
                        "id":"1133223473825570817",
                        "pid":"1133003248421167105",
                        "children":[
                            {
                                "id":"1133224268310634497",
                                "pid":"1133223473825570817",
                                "children":[
    
                                ],
                                "name":"标签列表",
                                "url":"mggoods/tag/list",
                                "type":0,
                                "icon":"",
                                "permissions":"",
                                "sort":1,
                                "createDate":null,
                                "resourceList":null,
                                "parentName":null
                            },
                            {
                                "id":"1133235434600652802",
                                "pid":"1133223473825570817",
                                "children":[
    
                                ],
                                "name":"属性分组",
                                "url":"mggoods/tag/group",
                                "type":0,
                                "icon":"",
                                "permissions":"",
                                "sort":2,
                                "createDate":null,
                                "resourceList":null,
                                "parentName":null
                            }
                        ],
                        "name":"标签管理",
                        "url":"",
                        "type":0,
                        "icon":"icon-tags",
                        "permissions":"",
                        "sort":6,
                        "createDate":null,
                        "resourceList":null,
                        "parentName":null
                    }
                ],
                "name":"商品",
                "url":"",
                "type":0,
                "icon":"icon-check-circle",
                "permissions":"",
                "sort":1,
                "createDate":null,
                "resourceList":null,
                "parentName":null
            },
            {
                "id":"2",
                "pid":"0",
                "children":[
                    {
                        "id":"14",
                        "pid":"2",
                        "children":[
                            {
                                "id":"22",
                                "pid":"14",
                                "children":[
    
                                ],
                                "name":"订单列表",
                                "url":"mgorder/order/list",
                                "type":0,
                                "icon":"icon-lock",
                                "permission":null,
                                "sort":1
                            }
                        ],
                        "name":"订单管理",
                        "url":"11",
                        "type":0,
                        "icon":"icon-lock",
                        "permission":null,
                        "sort":1
                    },
                    {
                        "id":"15",
                        "pid":"2",
                        "children":[
                            {
                                "id":"24",
                                "pid":"15",
                                "children":[
    
                                ],
                                "name":"售后审核",
                                "url":"mgorder/aftersalelist/index",
                                "type":0,
                                "icon":"icon-lock",
                                "permission":null,
                                "sort":1
                            },
                            {
                                "id":"23",
                                "pid":"15",
                                "children":[
    
                                ],
                                "name":"退货管理",
                                "url":"mgorder/returngoods/index",
                                "type":0,
                                "icon":"icon-lock",
                                "permission":null,
                                "sort":2
                            },
                            {
                                "id":"25",
                                "pid":"15",
                                "children":[
    
                                ],
                                "name":"换货管理",
                                "url":"mgorder/exchangegoods/index",
                                "type":0,
                                "icon":"icon-dashboard-fill",
                                "permission":null,
                                "sort":3
                            }
                        ],
                        "name":"售后管理",
                        "url":"11",
                        "type":0,
                        "icon":"icon-lock",
                        "permission":null,
                        "sort":2
                    }
                ],
                "name":"订单",
                "url":"22",
                "type":0,
                "icon":"icon-lock",
                "permission":"11",
                "sort":2
            },
            {
                "id":"3",
                "pid":"0",
                "children":[
                    {
                        "id":"16",
                        "pid":"3",
                        "children":[
    
                        ],
                        "name":"店铺优惠券",
                        "url":"11",
                        "type":0,
                        "icon":"icon-lock",
                        "permission":null,
                        "sort":1
                    }
                ],
                "name":"营销",
                "url":"33",
                "type":0,
                "icon":"icon-lock",
                "permission":"11",
                "sort":3
            },
            {
                "id":"4",
                "pid":"0",
                "children":[
                    {
                        "id":"17",
                        "pid":"4",
                        "children":[
    
                        ],
                        "name":"交易统计",
                        "url":"11",
                        "type":0,
                        "icon":"icon-lock",
                        "permission":null,
                        "sort":1
                    },
                    {
                        "id":"18",
                        "pid":"4",
                        "children":[
    
                        ],
                        "name":"商品统计",
                        "url":"11",
                        "type":0,
                        "icon":"icon-lock",
                        "permission":null,
                        "sort":2
                    }
                ],
                "name":"统计",
                "url":"222",
                "type":0,
                "icon":"icon-lock",
                "permission":null,
                "sort":4
            },
            {
                "id":"5",
                "pid":"0",
                "children":[
                    {
                        "id":"19",
                        "pid":"5",
                        "children":[
    
                        ],
                        "name":"商家结算",
                        "url":"11",
                        "type":0,
                        "icon":"icon-lock",
                        "permission":null,
                        "sort":1
                    }
                ],
                "name":"财务",
                "url":"333",
                "type":0,
                "icon":"icon-lock",
                "permission":null,
                "sort":5
            },
            {
                "id":"6",
                "pid":"0",
                "children":[
                    {
                        "id":"20",
                        "pid":"6",
                        "children":[
    
                        ],
                        "name":"图片库",
                        "url":"content/pictures",
                        "type":0,
                        "icon":"icon-lock",
                        "permission":null,
                        "sort":1
                    }
                ],
                "name":"内容",
                "url":"333",
                "type":0,
                "icon":"icon-lock",
                "permission":null,
                "sort":6
            },
            {
                "id":"7",
                "pid":"0",
                "children":[
                    {
                        "id":"21",
                        "pid":"7",
                        "children":[
    
                        ],
                        "name":"店铺设置",
                        "url":"store/index",
                        "type":0,
                        "icon":"icon-lock",
                        "permission":null,
                        "sort":1
                    },
                    {
                        "id":"26",
                        "pid":"7",
                        "children":[
    
                        ],
                        "name":"登录日志",
                        "url":"store/login",
                        "type":null,
                        "icon":"icon-lock",
                        "permission":null,
                        "sort":2
                    }
                ],
                "name":"店铺",
                "url":"333",
                "type":0,
                "icon":"icon-lock",
                "permission":null,
                "sort":7
            }
        ]
}

